FileVersion = 1

[Project]
Name = "Sqlite-Beef"
TargetType = "BeefLib"
StartupObject = "Sqlite_Beef.Program"

[Configs.Release.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/deps/*.dll\")"]
